### ISSUE TITLE
Resolve deprection: Using this.$() in a component has been deprecated

### ISSUE THREAD

**Issue by jenweber** [cardstack/ember-toolbars#16]
I think we can resolve this by installing `@ember/jquery` and replacing this.$ with a jquery import.

> DEPRECATION: Using this.$() in a component has been deprecated, consider using this.element [deprecation id: ember-views.curly-components.jquery-element] See https://emberjs.com/deprecations/v3.x#toc_jquery-apis for more details.

**Comment by ef4** [comment]
That would be OK.

It would also be straightforward to switch from liquid-fire to ember-animated, which would eliminate the need for the jquery-wrapped element.
